Prevent README.md from being messed up in case of GitHub issues
Signed-off-by: Wouter Born <github@maindrain.net>

diff --git a/helper-functions b/helper-functions
--- a/helper-functions
+++ b/helper-functions
@@ -138,6 +138,11 @@ generate_readme_versions() {
 update_readme() {
 	local file=README.md
 
+	if [ "$(last_stable_version)" == "" ]; then
+		echo "Cannot update $file because the last stable version is unknown!"
+		exit 1
+	fi
+
 	local generate="false"
 	while IFS= read -r line
 	do
