Fix time zone detection issues (#487)
Since OpenJDK 21.0.10 /etc/timezone is no longer used to detect the default JVM time zone (JDK-8345213).

* Update /etc/localtime symlink based on TZ environment variable
* Install missing tzdata package in Alpine image
* Update documentation

Fixes #485

Signed-off-by: Wouter Born <github@maindrain.net>

diff --git a/debian/entrypoint b/debian/entrypoint
--- a/debian/entrypoint
+++ b/debian/entrypoint
@@ -4,6 +4,22 @@ interactive=$(if test -t 0; then echo true; else echo false; fi)
 set -eux -o pipefail ${EXTRA_SHELL_OPTS-}
 IFS=$'\n\t'
 
+# Configure time zone
+if [ -n "${TZ:-}" ]; then
+  if mountpoint -q /etc/localtime; then
+    echo "Warning: /etc/localtime is mounted. Please remove this volume mount and use the TZ environment variable instead."
+  else
+    if [ ! -f "/usr/share/zoneinfo/${TZ}" ]; then
+      echo "Error: Invalid timezone '${TZ}' set in TZ environment variable" >&2
+      exit 1
+    fi
+    ln -sf "/usr/share/zoneinfo/${TZ}" /etc/localtime
+  fi
+else
+  echo "TZ environment variable is not set. Skipping time zone configuration."
+fi
+
+# Determine Java home directory independent of JVM vendor, version and environment variables
 export JAVA_HOME=$(find /usr/lib/jvm -mindepth 1 -maxdepth 1 -type d)
 
 # Configure Java unlimited strength cryptography
