Automatically run upgrade tool (#419)
Similar to openhab/openhab-distro#1532

Signed-off-by: Wouter Born <github@maindrain.net>

diff --git a/debian/update b/debian/update
--- a/debian/update
+++ b/debian/update
@@ -189,6 +189,17 @@ if [ -f "$addons_file" ]; then
 fi
 echo ""
 
+# Start the upgrade tool
+if [ -f "${OPENHAB_HOME}/runtime/bin/upgradetool.jar" ]; then
+  echo "Starting JSON database update..."
+  java -jar "${OPENHAB_HOME}/runtime/bin/upgradetool.jar" || {
+    echo "Update tool failed, please check the openHAB website (www.openhab.org) for manual update instructions." >&2
+    exit 1
+  }
+  echo "JSON database updated successfully."
+  echo ""
+fi
+
 echo ""
 echo "SUCCESS: openHAB updated from ${current_version} to ${oh_version}"
 echo ""
